apiVersion: v1
kind: Namespace
metadata:
  name: sre-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-demo
  namespace: sre-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-demo
  template:
    metadata:
      labels:
        app: crash-demo
    spec:
      containers:
      - name: app
        image: polinux/stress
        args: ["--vm", "1", "--vm-bytes", "200M"]
        resources:
          limits:
            memory: "64Mi"